### PR TITLE
Lower ecam -  ELEC page

### PR DESCRIPTION
**Pull request by merspieler**
### Description of Changes
Changes to the ELEC ECAM page.

I open this for you to keep track of my changes

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [x] Please have an IDG Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
@it0uchpods I do not know if this conflicts with my improvements. It needs testing. Could I test it before you merge?

**Comment by merspieler** [comment]
> * [ ] My changes are ready for merging. &lt;!-- Uncheck if you want to decide when to merge. --&gt;

This isn't ready for merge yet...

**Comment by legoboyvdlp** [comment]
Alright, let me know when it is ready. And it should NOT overwrite any of my changes!

**Comment by it0uchpods** [comment]
Due to the amount of changes, I want to check this personally before it is merged.

I'll try to do it today.

Josh

**Comment by it0uchpods** [comment]
Well, I want to make sure it is working well and good quality before it's merged, due to the amount of changes.

Josh

**Comment by legoboyvdlp** [comment]
Yes, that is most certainly a good idea. Please go ahead and check it, @it0uchpods  => hopefully it did not overwrite my changes.

Thanks for your work, @merspieler !

**Pull request merged**
