### PR TITLE
UnBroken autopush

### PR DESCRIPTION
**Pull request by merspieler**
### Description of Changes
default:
    break;

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [ ] Please have an IDG Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by it0uchpods** [comment]
Why did you remove acconfig.writeSettings? It now won't save that setting........

**Comment by merspieler** [comment]
let me check...

**Comment by merspieler** [comment]
Happy?

**Comment by it0uchpods** [comment]
You ignored my note; 

So no, not yet. Check pls.

Pls move the autopush config back into -main. -main is where things are setup, I don't want so many loose files with no need to exist.

**Comment by merspieler** [comment]
I've fixed it... if you want to rearange please do so your self

**Comment by it0uchpods** [comment]
OK, I'll do it when i got time -- which won't be for a bit since I'm not home, and I'm busy with FMGC

BTW: pls see my note above again -- github removed part of it before some reason.

**Comment by merspieler** [comment]
ik... cause i've merged my private dev branch which does reflect the autopush repo... not any IDG specific things...

**Pull request closed without merging**
