### PR TITLE
Added functionality to the RMP

### PR DESCRIPTION
**Pull request by merspieler**
### Description of Changes
* Added VHF1, VHF2 and VHF3 fully functional
* All Channel keys selectable

### TODO
* Cosmetic stuff
* Add the RMPs to the autostart and shutdown sequences
* Add power consumption (RMP1 on DC-ESS, RMP2 on DC-2)
* HF and STBY NAV dialing
* When `/instrumentation/comm[2]/frequencies/selected-mhz` != 0 display ecam messages:
    * On the right side `VHF3 VOICE`
    * On the left side `COMPANY DATALINK STBY`

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [x] Please have an IDG Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
See 777 for how to add extra radios.

**Comment by merspieler** [comment]
Where (in which file) do i have to look?

**Comment by legoboyvdlp** [comment]
See Systems/tranceivers.xml, Systems/instrumentation.xml

**Comment by legoboyvdlp** [comment]
1. Please make the color of the displays orange, not white
2. Add RMP power to acconfig.
3. Add the third radio to the radio dialog

**Pull request merged**
