### PR TITLE
Air Data

### PR DESCRIPTION
**Pull request by legoboyvdlp**
### Description of Changes
Add's realistic air data simulation including probe falures

### Checklist:

* [X] My changes follow the Contributing Guidelines. 
* [X] My changes implement realistic features. 
* [X] Please have an IDG Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by merspieler** [comment]
The switch on the SWITCHING panel can't be used as expected (compared to how the other elements in the aircraft can be used.).
On Mouse wheel up, all knobs rotate clock wise except this one.

VSI still forks on fault... How do you calculate VS without static port? please check.

Speed change tendence (yellow arrow) isn't shown correct. Even on non faulty system when a fault occures.

**Comment by legoboyvdlp** [comment]
I am not calculating it myself when there is a working one there, it is a waste of performance. The bugfix will be in next in a few days, and once 2018.3.2 is the stable release I can fix the vertical speed. Meanwhile I will create 3 seperate generic vertical speed indicators and route the static pressure to them - (the bug is that it cannot take my adjusted static pressure from jsbsim, returns a NaN)

What bug when changing QNH?

**Comment by merspieler** [comment]
When QNH changes cause you move from one area to another with different QNH

**Comment by legoboyvdlp** [comment]
That's not a bug...

Pressure altitude decreases, so it climbs to maintain altitude.

**Comment by merspieler** [comment]
For the knob animation: changes this file Models/Instruments/Pedestal_up/Pedestal_up.xml

if you give me a few min, i can write you the lines

**Comment by merspieler** [comment]
@legoboyvdlp check which prop the a/thr uses... currently if capt pitot fails, a/thr goes crazy...

**Comment by legoboyvdlp** [comment]
I know which file to modify, given I was the person that originally animated the knob.. regardless, I will see if the autothrust needs fixing or not. I think if the pitot fails the autothrust should automatically disconnect.

**Comment by legoboyvdlp** [comment]
@merspieler 
image

vertical speed is calculated with inertial data. So it will still be present if air data has any failure

once I simulate the IR part of ADIRS (later!) baro-inertial switching can be simulated.

**Comment by merspieler** [comment]
ok, i didn't knew that

**Comment by it0uchpods** [comment]
I will look into this this weekend or earlier.

**Comment by legoboyvdlp** [comment]
ready pending your comments

**Comment by it0uchpods** [comment]
Great!
I will merge this locally, resolve the conflicts, and test. I'll let you know.

J

**Comment by legoboyvdlp** [comment]
Thanks!

**Pull request merged**
